line:
  bot:
    channel-token: "msU4rXQ8nhLgjEeQjBNp7nW7MBJ1N9aD5la31SbxYIHVqDMdOGS4E1w707Vi/1F6u2WiVv5Q2CMIViUKvyczhQ8A36evavyganSoMmAZXLh6240hitigBuGuYcheLBxigb9Q+la+zqA9v4YP+KLQqQdB04t89/1O/w1cDnyilFU="
    channel-secret: "586cf0a1d6af41b7d3a0843d66cb67fd"

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:}